#!/usr/bin/env bash

tar -zc --exclude wordpress/wp-content/themes/bucket-api/app/node_modules/ wordpress/wp-content/themes/bucket-api | ssh root@littlebigberry.com "cat > ~/file.tar.gz && tar -zxvf file.tar.gz && rm -rf /var/www/wp-content/themes/bucket-api/ && cp -r ~/wordpress/wp-content/themes/bucket-api/ /var/www/wp-content/themes/bucket-api/ && rm -rf file.tar.gz && rm -rf wordpress/"